// app/src/renderer/components/TitleBar.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ipc } from '@/composables/useIpc'

defineProps<{ module: string; item: string }>()

const maximized = ref(false)

async function toggleMaximize(): Promise<void> {
  maximized.value = await ipc.window.toggleMaximize()
}

onMounted(async () => {
  maximized.value = await ipc.window.isMaximized()
})
</script>

<template>
  <header class="drag-region flex items-center justify-between border-b border-line bg-surface pl-4">
    <div class="flex items-center gap-3">
      <div class="bg-brand flex h-6 w-6 items-center justify-center rounded-md text-[11px] font-bold text-white">
        CV
      </div>
      <span class="text-sm font-semibold">Chatvein</span>
      <span class="text-ink-soft text-xs">{{ module }} / {{ item }}</span>
    </div>

    <div class="no-drag flex h-full items-center">
      <button
        class="text-ink-soft hover:bg-surface-2 hover:text-ink flex h-full w-11 items-center justify-center text-xs transition-colors"
        title="最小化"
        @click="ipc.window.minimize()"
      >
        &#8211;
      </button>
      <button
        class="text-ink-soft hover:bg-surface-2 hover:text-ink flex h-full w-11 items-center justify-center text-xs transition-colors"
        :title="maximized ? '还原' : '最大化'"
        @click="toggleMaximize"
      >
        {{ maximized ? '&#10064;' : '&#9723;' }}
      </button>
      <button
        class="text-ink-soft flex h-full w-11 items-center justify-center text-xs transition-colors hover:bg-red-500 hover:text-white"
        title="关闭"
        @click="ipc.window.close()"
      >
        &#10005;
      </button>
    </div>
  </header>
</template>

// src/components/layout/TitleBar.tsx
import { getCurrentWindow } from "@tauri-apps/api/window";
import { type ReactNode } from "react";
import { cn } from "../../lib/cn";

async function withWindow(fn: (win: ReturnType<typeof getCurrentWindow>) => Promise<void>) {
  try {
    await fn(getCurrentWindow());
  } catch {
    // Browser preview without Tauri — no-op.
  }
}

function WinButton({
  title,
  danger,
  onClick,
  children,
}: {
  title: string;
  danger?: boolean;
  onClick: () => void;
  children: ReactNode;
}) {
  return (
    <button
      type="button"
      title={title}
      onClick={onClick}
      className={cn(
        "flex w-[46px] items-center justify-center text-ink-400 transition-colors",
        "focus-visible:outline-2 focus-visible:outline-brand-600",
        danger
          ? "hover:bg-danger-600 hover:text-white"
          : "hover:bg-tint-deep hover:text-ink-700"
      )}
    >
      {children}
    </button>
  );
}

export function WindowControls() {
  return (
    <div className="flex shrink-0 items-stretch">
      <WinButton
        title="最小化"
        onClick={() => void withWindow((w) => w.minimize())}
      >
        <svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
          <path d="M0 5h10" stroke="currentColor" strokeWidth="1" />
        </svg>
      </WinButton>
      <WinButton
        title="最大化"
        onClick={() =>
          void withWindow(async (w) => {
            if (await w.isMaximized()) await w.unmaximize();
            else await w.maximize();
          })
        }
      >
        <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
          <rect
            x="0.5"
            y="0.5"
            width="9"
            height="9"
            rx="1.5"
            stroke="currentColor"
            strokeWidth="1"
          />
        </svg>
      </WinButton>
      <WinButton
        title="关闭"
        danger
        onClick={() => void withWindow((w) => w.close())}
      >
        <svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
          <path
            d="M0.5 0.5l9 9M9.5 0.5l-9 9"
            stroke="currentColor"
            strokeWidth="1"
            strokeLinecap="round"
          />
        </svg>
      </WinButton>
    </div>
  );
}

export function TitleBar({ title = "ChatVein" }: { title?: string }) {
  return (
    <header className="flex h-9 shrink-0 items-stretch bg-page">
      <div className="flex min-w-0 flex-1 items-center pl-3" data-tauri-drag-region>
        <span className="flex items-center gap-1.5" data-tauri-drag-region>
          <span
            className="flex size-5 shrink-0 items-center justify-center rounded-md bg-brand-600 text-[10px] font-bold text-white"
            data-tauri-drag-region
          >
            C
          </span>
          <span className="text-[11.5px] font-medium text-ink-500" data-tauri-drag-region>
            {title}
          </span>
        </span>
        <span className="min-w-0 flex-1" data-tauri-drag-region />
      </div>
      <WindowControls />
    </header>
  );
}
